### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by evamia2007** [jonathanqv/cmip6d#2]
Hello!

I run my script using Jupiter Notebook:
from cmip6d import cmip6d
out_path = 'G:/NEX-GDDP-CMIP6' # Defines your output folder
coords = [95,107.5,-6,7] # xmin,xmax,ymin,ymax
models = ['UKESM1-0-LL'] # If empty, downloads everything, if not, downloads specified packages
ssp=['historical','ssp370'] # DEFAULT VARIABLE. Target scenarios from the NASA server
variables = ['pr','tasmin','tasmax','tas','hurs','rlds','rsds','sfcWind'] # DEFAULT VARIABLE. Target variables from the NASA server
cc = cmip6d(out_path,coords,models,variables=variables,ssp=ssp)
cc.get_links(out_path,check_links=True)
#cc.download_links(nworker=6)
#cc.merge_files(cont=True)

and got this error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18832\273327843.py in <module>
      6 variables = ['pr','tasmin','tasmax','tas','hurs','rlds','rsds','sfcWind'] # DEFAULT VARIABLE. Target variables from the NASA server
      7 cc = cmip6d(out_path,coords,models,variables=variables,ssp=ssp)
----> 8 cc.get_links(out_path,check_links=True)
      9 #cc.download_links(nworker=6)
     10 #cc.merge_files(cont=True)

~\AppData\Roaming\Python\Python39\site-packages\cmip6d\cmip6d.py in get_links(self, out_path, check_links)
     62         # Model level
     63         #.______________________
---> 64         level1= self.url_lv(URL_BASE+self.URL_END,URL_BASE)
     65         for url_1,name_1 in level1:
     66             token = False

~\AppData\Roaming\Python\Python39\site-packages\cmip6d\cmip6d.py in url_lv(self, url, URL_BASE, final)
     50                     pass
     51                 else:
---> 52                     urls_lv_list.append([URL_BASE+row['href'],row.tt.text])
     53         return urls_lv_list
     54     def get_links(self,out_path,check_links=False):

AttributeError: 'NoneType' object has no attribute 'text'

Do you know why this happens?

**Comment by jonathanqv** [comment]
Hey,

This is happening now because the "https://ds.nccs.nasa.gov/thredds/catalog/AMES/NEX/GDDP-CMIP6/catalog.html" server is down, which is weird. Oddly enough, if you use a generated link from the get_links function, it is downloaded, see an example below. Looks like their Amazon Web server is working but not the catalog one which allows spatial filters.

A solution to this problem is to create the links without querying the catalog, but waiting for the server to be up again is a better idea.


https://ds.nccs.nasa.gov/thredds/ncss/grid/AMES/NEX/GDDP-CMIP6//UKESM1-0-LL/ssp245/r1i1p1f2/pr/pr_day_UKESM1-0-LL_ssp245_r1i1p1f2_gn_2015.nc?var=pr&north=52&west=0&east=1&south=51&disableProjSubset=on&horizStride=1&time_start=2015-01-01T12%3A00%3A00Z&time_end=2015-12-30T12%3A00%3A00Z&timeStride=1&addLatLon=true

**Comment by jonathanqv** [comment]
It should be working now!
